### ISSUE TITLE
Enabling Bootstrap Colorpicker in Admin Panel

### ISSUE THREAD

**Issue by Norwayman** [septor/bootstrap-colorpicker#1]
Enabling the Bootstrap Colorpicker in Admin Panel and hitting SAVE does not SAVE the choice.
When I go back to see if it saved it to ENABLED it still is on DISABLED.
I am using V2 of E107, FireFox and WampServer.

**Comment by septor** [comment]
Ah, yeah.

You can fix this by renaming the folder to `bootstrap_colorpicker`. When naming this I forgot you can't use hyphens in class names. I've adjusted the repo accordingly so this won't happen in the future.
